name:  Unchained Launcher CI Tests

on:
  push:
    branches:
        - 'main'
  pull_request:
    branches:
        - 'main'
        - 'series/*'

# TODO: Run integration tests. Set up some kind of stubbed environment for the tests to run in.
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    env:
      GUI_Project_Path: UnchainedLauncher.GUI
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.AUTOMATED_CODE_CHANGE }}

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'


    - name: Format source
      run: dotnet format
    - uses: stefanzweifel/git-auto-commit-action@v5
      id: auto-commit-action
      with:
        commit_message: '[GHA] Format Source' 

    - name: Fail if changes were detected
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      run: exit 1

        
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c ${{ matrix.configuration }}
    - name: Run Unit Tests
      run: dotnet test -c ${{ matrix.configuration }} .\UnchainedLauncher.Core.Tests.Unit\

    # Puts binaries in ${{ env.GUI_Project_Path }}\bin\${{ matrix.configuration }}\net6.0-windows\win-x64\publish\
    - name: Package ${{ matrix.configuration }} binaries
      run: dotnet publish -c ${{ matrix.configuration}} 

    - name: Upload ${{ matrix.configuration }} Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: UnchainedLauncher_${{ matrix.configuration }}_${{ github.sha }}
        path: ${{ env.GUI_Project_Path }}\bin\${{ matrix.configuration }}\net6.0-windows\win-x64\publish\

