name:  Unchained Launcher Tag Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x64]
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      GUI_Project_Path: UnchainedLauncherGUI

    steps:
        - uses: actions/checkout@v4
        - name: Setup dotnet
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '6.x'
        - name: Install dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build
        - name: Run Unit Tests
          run: dotnet test .\UnchainedLauncherCoreTests\

        # Puts binaries in UnchainedLauncherGUI\bin\Debug\net6.0-windows\win-x64\publish\
        - name: Package Debug binaries
          run: dotnet publish -c Debug 

        # Puts binaries in UnchainedLauncherGUI\bin\Release\net6.0-windows\win-x64\publish\
        - name: Package Release binaries
          run: dotnet publish -c Release

        - name: Create GitHub Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: "Release ${{ github.ref }}: ${{ env.tag_annotation }}"
            draft: false
            prerelease: true
            body: |
              ${{ github.ref }}

        # Add Release assets
        - name: Upload Release Launcher
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: results/Release/net6.0-windows/win-x64/publish/UnchainedLauncher.exe
            asset_name: UnchainedLauncher.exe
            asset_content_type: application/octet-stream

        - name: Upload Debug Launcher
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: results/Debug/net6.0-windows/win-x64/publish/UnchainedLauncher.exe
            asset_name: UnchainedLauncher_dbg.exe
            asset_content_type: application/octet-stream

        - name: Upload Debug Launcher PDB
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: results/Debug/net6.0-windows/win-x64/publish/UnchainedLauncher.pdb
            asset_name: UnchainedLauncher.pdb
            asset_content_type: application/octet-stream